[package]
edition = '2021'
name = "ton_executor"
version = "2.0.0"

[dependencies]
everscale-vm = { git = "https://github.com/broxus/ton-labs-vm.git", package = "ton_vm", branch = "new_cells" }
everscale-types = { git = "https://github.com/broxus/everscale-types.git", features = ["stats"], branch = "feature/msgs-proc-logic" }

# External
ahash = "0.8"
anyhow = "1.0.79"
thiserror = "1.0"
tracing = "0.1"